# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTg69dERZCQtUF-Ui7TpeCMHGzJfXABC
"""
import streamlit as st
import numpy as np
from PIL import Image
import joblib

# ----------------------------
# Page Config
# ----------------------------
st.set_page_config(
    page_title="Male vs Female Classifier",
    page_icon="👤",
    layout="centered"
)

# ----------------------------
# Custom CSS
# ----------------------------
st.markdown("""
<style>

.main {
    background-color: #0f172a;
}

h1{
    text-align:center;
}

.big-font{
    font-size:18px !important;
    text-align:center;
    color:#b8c1ec;
}

.prediction{
    padding:18px;
    border-radius:12px;
    text-align:center;
    font-size:28px;
    font-weight:bold;
    margin-top:15px;
}

.footer{
    text-align:center;
    color:gray;
    margin-top:40px;
}

</style>
""", unsafe_allow_html=True)

# ----------------------------
# Sidebar
# ----------------------------
st.sidebar.title("📌 Project Info")

st.sidebar.info("""
### Male vs Female Classifier

**Model:** Logistic Regression

**Image Size:** 64 × 64

**Framework:** Streamlit

**Libraries Used**
- NumPy
- Pillow
- Scikit-learn
- Joblib

Built during Summer Training 🚀
""")

# ----------------------------
# Load Model
# ----------------------------
model = joblib.load("male_female_model.pkl")

IMG_SIZE = 64

# ----------------------------
# Header
# ----------------------------
st.markdown(
    "<h1>👤 Male vs Female Image Classifier</h1>",
    unsafe_allow_html=True,
)

st.markdown(
    "<p class='big-font'>Upload a face image and let the Machine Learning model predict the gender.</p>",
    unsafe_allow_html=True,
)

st.divider()

# ----------------------------
# Upload
# ----------------------------
uploaded_file = st.file_uploader(
    "📤 Upload an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )

    # ----------------------------
    # Preprocessing
    # ----------------------------
    img = image.resize((IMG_SIZE, IMG_SIZE))
    img = np.array(img, dtype=np.float32)
    img = img / 255.0
    img = img.flatten()
    img = img.reshape(1, -1)

    # ----------------------------
    # Prediction
    # ----------------------------
    prediction = model.predict(img)[0]
    probability = model.predict_proba(img)[0]

    st.divider()

    st.subheader("Prediction")

    if prediction == 0:
        st.success("👨 Male")
    else:
        st.success("👩 Female")

    st.subheader("Confidence")

    male = float(probability[0])
    female = float(probability[1])

    st.write(f"👨 Male : **{male*100:.2f}%**")
    st.progress(male)

    st.write(f"👩 Female : **{female*100:.2f}%**")
    st.progress(female)

    st.divider()

    st.info(
        "⚠️ This project is built for educational purposes using Logistic Regression. "
        "Predictions may not always be accurate."
    )

# ----------------------------
# Footer
# ----------------------------
st.markdown(
"""
<div class="footer">

Made with ❤️ using Streamlit & Scikit-Learn

</div>
""",
unsafe_allow_html=True)


    
