# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTg69dERZCQtUF-Ui7TpeCMHGzJfXABC
"""
import streamlit as st
import numpy as np
from PIL import Image
import joblib

# -------------------------------------------------
# PAGE CONFIG
# -------------------------------------------------

st.set_page_config(
    page_title="Male Vs Female Classifier",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# -------------------------------------------------
# LOAD MODEL
# -------------------------------------------------

model = joblib.load("male_female_model.pkl")

IMG_SIZE = 64

# -------------------------------------------------
# CUSTOM CSS
# -------------------------------------------------

st.markdown("""
<style>

#MainMenu{
visibility:hidden;
}

footer{
visibility:hidden;
}

header{
visibility:hidden;
}

.main{

background:#0f172a;

}

.block-container{

padding-top:2rem;

padding-left:4rem;

padding-right:4rem;

padding-bottom:2rem;

}

.title{

font-size:58px;

font-weight:800;

text-align:center;

background:linear-gradient(90deg,#00F5FF,#7B2FF7,#FF00E5);

-webkit-background-clip:text;

-webkit-text-fill-color:transparent;

margin-bottom:0px;

}

.subtitle{

text-align:center;

font-size:20px;

color:#cbd5e1;

margin-top:-10px;

margin-bottom:35px;

}

.uploadBox{

padding:25px;

border-radius:18px;

background:#1e293b;

border:1px solid #334155;

}

.predictionCard{

background:#1e293b;

padding:30px;

border-radius:20px;

border:1px solid #334155;

box-shadow:0px 0px 25px rgba(0,255,255,0.08);

}

.infoCard{

background:#172554;

padding:18px;

border-radius:15px;

border-left:5px solid cyan;

}

.metricCard{

background:#111827;

padding:18px;

border-radius:18px;

text-align:center;

}

.footer{

text-align:center;

margin-top:60px;

font-size:15px;

color:gray;

}

div[data-testid="stMetric"]{

background:#111827;

padding:18px;

border-radius:15px;

border:1px solid #334155;

}

.stProgress>div>div{

background:linear-gradient(to right,#06b6d4,#8b5cf6);

}

</style>

""",unsafe_allow_html=True)

# -------------------------------------------------
# HEADER
# -------------------------------------------------

st.markdown(
"""
<div class='title'>
👤 Male vs Female Classifier
</div>
""",
unsafe_allow_html=True
)

st.markdown(
"""
<div class='subtitle'>
Upload a face image and let the model predict whether it is Male or Female.
</div>
""",
unsafe_allow_html=True
)

st.divider()

# -------------------------------------------------
# PROJECT INFO
# -------------------------------------------------

with st.expander("📌 About this Project"):

    st.markdown("""
### Technology Used

- 🧠 Logistic Regression
- 🌐 Streamlit
- 🖼 Pillow
- 🔢 NumPy
- 💾 Joblib

---

This project demonstrates image classification using Machine Learning.

The uploaded image is resized to **64 × 64**, converted into numerical features, and passed to a trained Logistic Regression model for prediction.
""")

# -------------------------------------------------
# FILE UPLOADER
# -------------------------------------------------

uploaded_file = st.file_uploader(

"📤 Upload a Face Image",

type=["jpg","jpeg","png"]

)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1,col2 = st.columns([1.2,1])

    with col1:

        st.image(
            image,
            caption="Uploaded Image",
            use_container_width=True
        )

    with col2:

        st.markdown("## 🎯 Prediction")

        st.info("Processing Image...")

        # Image Preprocessing

        img = image.resize((IMG_SIZE,IMG_SIZE))

        img = np.array(img,dtype=np.float32)

        img = img/255.0

        img = img.flatten()

        img = img.reshape(1,-1)
# --------------------------------------------
        # Prediction
        # --------------------------------------------

        prediction = model.predict(img)[0]

        probability = model.predict_proba(img)[0]

        male_prob = float(probability[0])

        female_prob = float(probability[1])

        confidence = max(male_prob, female_prob)

        st.toast("Prediction Completed 🎉")

        st.balloons()

        st.markdown("<br>", unsafe_allow_html=True)

        # --------------------------------------------
        # Prediction Card
        # --------------------------------------------

        if prediction == 0:

            st.markdown(
                """
                <div class='predictionCard'>

                <h1 style='text-align:center;color:#38bdf8;'>

                👨 MALE

                </h1>

                </div>
                """,
                unsafe_allow_html=True
            )

        else:

            st.markdown(
                """
                <div class='predictionCard'>

                <h1 style='text-align:center;color:#ec4899;'>

                👩 FEMALE

                </h1>

                </div>
                """,
                unsafe_allow_html=True
            )

        st.markdown("<br>", unsafe_allow_html=True)

        # --------------------------------------------
        # Metrics
        # --------------------------------------------

        metric1, metric2 = st.columns(2)

        with metric1:

            st.metric(

                "Prediction",

                "👨 Male" if prediction == 0 else "👩 Female"

            )

        with metric2:

            st.metric(

                "Confidence",

                f"{confidence*100:.2f}%"

            )

        st.markdown("---")

        # --------------------------------------------
        # Confidence Bars
        # --------------------------------------------

        st.subheader("📊 Confidence Score")

        st.write(f"👨 Male : **{male_prob*100:.2f}%**")

        st.progress(male_prob)

        st.write("")

        st.write(f"👩 Female : **{female_prob*100:.2f}%**")

        st.progress(female_prob)

        st.markdown("---")

        # --------------------------------------------
        # Result Message
        # --------------------------------------------

        if confidence > 0.90:

            st.success(
                "The model is highly confident about this prediction."
            )

        elif confidence > 0.70:

            st.info(
                "The prediction confidence is reasonably high."
            )

        else:

            st.warning(
                "The confidence is low. This may happen if the uploaded image "
                "is blurry, has poor lighting, or differs from the training data."
            )

        # --------------------------------------------
        # Probability Table
        # --------------------------------------------

        st.subheader("📋 Prediction Summary")

        st.dataframe(

            {
                "Class": ["Male", "Female"],
                "Probability": [
                    f"{male_prob*100:.2f} %",
                    f"{female_prob*100:.2f} %"
                ]
            },

            use_container_width=True,
            hide_index=True

        )
# -------------------------------------------------
# MODEL DETAILS
# -------------------------------------------------

st.markdown("<br>", unsafe_allow_html=True)

st.subheader("📌 Model Information")

info1, info2, info3 = st.columns(3)

with info1:
    st.info("""
### 🧠 Algorithm

Logistic Regression
""")

with info2:
    st.info("""
### 🖼 Image Size

64 × 64 Pixels
""")

with info3:
    st.info("""
### 📂 Classes

Male

Female
""")

st.markdown("---")

# -------------------------------------------------
# TECH STACK
# -------------------------------------------------

st.subheader("⚙️ Tech Stack")

c1, c2, c3 = st.columns(3)

with c1:
    st.success("🐍 Python")

with c2:
    st.success("🧠 Scikit-Learn")

with c3:
    st.success("🌐 Streamlit")

c4, c5, c6 = st.columns(3)

with c4:
    st.success("📊 NumPy")

with c5:
    st.success("🖼 Pillow")

with c6:
    st.success("💾 Joblib")

st.markdown("---")

# -------------------------------------------------
# DISCLAIMER
# -------------------------------------------------

st.warning(
"""
### ⚠️ Disclaimer

This application is built for educational purposes.

The model is trained on a limited dataset using **Logistic Regression**, so predictions may not always be accurate or generalize well to all images.
"""
)

# -------------------------------------------------
# PROJECT HIGHLIGHTS
# -------------------------------------------------

with st.expander("🚀 What happens behind the scenes?"):

    st.markdown("""
### Workflow

1️⃣ Upload Image

⬇

2️⃣ Resize to **64 × 64**

⬇

3️⃣ Convert Image into Numerical Features

⬇

4️⃣ Logistic Regression Model

⬇

5️⃣ Predict Male / Female

⬇

6️⃣ Display Confidence Scores
""")

# -------------------------------------------------
# FOOTER
# -------------------------------------------------

st.markdown("<br><br>", unsafe_allow_html=True)

st.markdown(
"""
<div style="text-align:center;
padding:25px;
border-radius:18px;
background:#111827;
border:1px solid #334155;">

<h3 style="color:#38bdf8;">
👤 Male vs Female Classifier
</h3>

<p style="color:#cbd5e1;font-size:18px;">
Male vs Female Face Classification
</p>

<hr>

<p style="color:gray;">
Developed by ANUSHKA ⭐ using Python • Streamlit • Scikit-Learn
</p>

<p style="color:gray;">
Summer Training Project 2026
</p>

</div>
""",
unsafe_allow_html=True
)        
