# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTg69dERZCQtUF-Ui7TpeCMHGzJfXABC
"""
import streamlit as st
import numpy as np
from PIL import Image
import joblib

# -----------------------------------
# Page Configuration
# -----------------------------------

st.set_page_config(
    page_title="Male vs Female Classifier",
    page_icon="🤖",
    layout="wide"
)

# -----------------------------------
# Custom CSS
# -----------------------------------

st.markdown("""
<style>

html, body, [class*="css"]{
    font-family: 'Segoe UI';
}

.main{
    background:#0E1117;
}

.title{
    text-align:center;
    font-size:55px;
    font-weight:800;
    background: linear-gradient(90deg,#00DBDE,#FC00FF);
    -webkit-background-clip:text;
    -webkit-text-fill-color:transparent;
}

.subtitle{
    text-align:center;
    color:#BFBFBF;
    font-size:20px;
    margin-bottom:25px;
}

.card{

background:#1A1D24;

padding:25px;

border-radius:20px;

box-shadow:0px 0px 15px rgba(255,255,255,0.08);

}

.footer{

text-align:center;

margin-top:50px;

color:gray;

font-size:15px;

}

</style>
""", unsafe_allow_html=True)

# -----------------------------------
# Sidebar
# -----------------------------------

st.sidebar.title("📌 Project Information")

st.sidebar.markdown("""
### 👤 Male vs Female Classifier

**Algorithm**
- Logistic Regression

**Libraries**
- Streamlit
- NumPy
- Pillow
- Scikit-Learn
- Joblib

**Image Size**
64 × 64

---

Built as part of my Machine Learning Summer Training 🚀
""")

# -----------------------------------
# Load Model
# -----------------------------------

model = joblib.load("male_female_model.pkl")

IMG_SIZE = 64

# -----------------------------------
# Header
# -----------------------------------

st.markdown('<div class="title">🤖 Male vs Female Classifier</div>',
unsafe_allow_html=True)

st.markdown(
'<div class="subtitle">Upload an image and let Machine Learning make a prediction.</div>',
unsafe_allow_html=True
)

st.divider()

# -----------------------------------
# Upload
# -----------------------------------

uploaded = st.file_uploader(
"📂 Upload Image",
type=["jpg","jpeg","png"]
)

if uploaded:

    image = Image.open(uploaded).convert("RGB")

    img=image.resize((IMG_SIZE,IMG_SIZE))
    img=np.array(img,dtype=np.float32)/255.0
    img=img.flatten().reshape(1,-1)

    prediction=model.predict(img)[0]
    probability=model.predict_proba(img)[0]

    male=float(probability[0])
    female=float(probability[1])

    col1,col2=st.columns([1.2,1])

    # --------------------------
    # LEFT
    # --------------------------

    with col1:

        st.image(
            image,
            caption="Uploaded Image",
            use_container_width=True
        )

    # --------------------------
    # RIGHT
    # --------------------------

    with col2:

        st.markdown("## 🎯 Prediction")

        if prediction==0:

            st.success("## 👨 MALE")

            confidence=male

        else:

            st.success("## 👩 FEMALE")

            confidence=female

        st.metric(
            label="Model Confidence",
            value=f"{confidence*100:.2f}%"
        )

        st.markdown("---")

        st.write("### 📊 Probability")

        st.write(f"👨 Male : **{male*100:.2f}%**")

        st.progress(male)

        st.write(f"👩 Female : **{female*100:.2f}%**")

        st.progress(female)

    st.balloons()

    st.divider()

    st.info(
        "⚠️ This project demonstrates image classification using Logistic Regression. "
        "Predictions may vary depending on the dataset used for training."
    )

# -----------------------------------
# Footer
# -----------------------------------

st.markdown("""
<div class="footer">

Made with ❤️ using Streamlit | Scikit-Learn | Python

</div>
""", unsafe_allow_html=True)
